#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"
#include "log.h"
#include <stdlib.h>
#include <assert.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix
// The input address is in host byte order.
// Tips:
// rtable is a global variable defined in rtable.c
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *best_match = NULL;
	rt_entry_t *rt_node;
	u32 max_mask = 0;

	list_for_each_entry(rt_node, &rtable, list) {
		u32 masked_dst = dst & rt_node->mask;
		u32 masked_entry = rt_node->dest & rt_node->mask;
		
		if (masked_dst == masked_entry) {
			if (!best_match || rt_node->mask > max_mask) {
				max_mask = rt_node->mask;
				best_match = rt_node;
			}
		}
	}
	return best_match;
}

// different from function ip_forward_packet, ip_send_packet sends packet generated by router itself
// This function is used to send icmp packets.
// You can complete this function after completing icmp_send_packet, or directly integrate the function into icmp_send_packet.
// The interface to sendd the packet is specified by longest_prefix_match.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *hdr = packet_to_ip_hdr(packet);
	u32 dst_ip = ntohl(hdr->daddr);
	
	rt_entry_t *route = longest_prefix_match(dst_ip);
	if (!route) {
		return;
	}

	u32 next_hop = route->gw;
	if (!next_hop) {
		next_hop = dst_ip;
	}

	iface_send_packet_by_arp(route->iface, next_hop, packet, len);
}
